### ISSUE TITLE
Xcode 7 GM / iOS 9 libMobileGestalt MobileGestalt.c:533: no access to UniqueDeviceID on device

### ISSUE THREAD

**Issue by jmoody** [calabash/run_loop#238]
Investigate.

Xcode 6 **Isolating the ScriptAgent no access to UniqueDeviceID bug** #34

**Comment by ysilyutin** [comment]
Hello,

I'm getting the same issue with the app during 'calabash-ios console' or 'cucumber'. Is there any update regarding this issue?

iphone-5-3 (9.1)
calabash-ios 0.16.4
/Applications/Xcode.app/Contents/Developer/
Xcode 7.1.1
Build version 7B1005
run_loop (2.0.1, 1.5.5) - checked both versions

Here is the command:
DEVICE_ENDPOINT=http://192.168.1.148:37265 DEVICE_TARGET=cffd6372f7a9c154b30764f8bfc653873d9289b6 APP_BUNDLE_PATH=~/Downloads/resigned/Payload/XXXXXX-tm.app/ BUNDLE_ID=com.XXXXXX.iphone calabash-ios console

Please let me know if you need any other information. Thank you.

**Comment by jmoody** [comment]
This is a bug in Apple's ScriptAgent.  We have no way of working around this.  I recommend restarting your device.  Is this causing problems during testing?

**Comment by ysilyutin** [comment]
Thank you, Josh for the quick response. 

Yes, the app started normally, but it stuck on the Splash screen and I don't see the steps execution or any errors on terminal. When I install and start the same build manually, I can see the Splash screen for about 3 secs and then the Home screen appears (expected behavior). Here is some log data from the Xcode:

`Dec  7 16:14:08 iphone-5-3 MobileGestaltHelper[86] <Error>: libMobileGestalt MobileGestalt.c:276: server_access_check denied access to question UniqueDeviceID for pid 180`
`Dec  7 16:14:08 iphone-5-3 ScriptAgent[180] <Error>: libMobileGestalt MobileGestaltSupport.m:151: pid 180 (ScriptAgent) does not have sandbox access for re6Zb+zwFKJNlkQTUeT+/w and IS NOT appropriately entitled`
`Dec  7 16:14:08 iphone-5-3 ScriptAgent[180] <Error>: libMobileGestalt MobileGestalt.c:537: no access to UniqueDeviceID (see <rdar://problem/11744455>)`
`Dec  7 16:14:10 iphone-5-3 useractivityd[132] <Error>: -[UAUserActivityClientProcess doUpdateUserActivityInfo:makeCurrent:completionHandler:], refusing to register user activity from client, and returning error Error Domain=UAContinuityErrorDomain Code=-108 "(null)" for item <__NSConcreteUUID 0x14e80db0> 714DC142-E84D-4FE4-898C-EC5BA77C0648 com.theapp.iphone.product.activityType (UAUserActivityClientProcess.m #1764)`

Any idea how can we fix it? I collaborate with developer, so we can try things into the Xcode project as well. Thank you in advance!

P.S. Device rebooting doesn't help unfortunately.

**Comment by jmoody** [comment]
How is your .ipa signed?

```
$ mkdir tmp
$ cp Your.ipa tmp/
$ cd tmp
$ unzip Your.ipa
$ cd Payload/
$ xcrun codesign --display --verbose=4 Your.app
```

I am guessing that the app is signed with a Distribution profile, probably an Ad Hoc profile.

**Comment by ysilyutin** [comment]
Thank you. Basically we are testing several apps (different companies/developers), some of them works fine, let me show you the status (below). We are using briar to resign each app with our developer certificate. Could you please suggest what profile should developer use for the build with calabash? Development, ad-hoc or distribution? Thank you in advance!

1. App A - doesn't work.
`Identifier=com.xxx.XXX.qa-tm`
`Format=bundle with Mach-O universal (armv7 arm64)`
`CodeDirectory v=20200 size=53703 flags=0x0(none) hashes=2676+5 location=embedded`
`Signature size=4357`
`Authority=iPhone Developer: XXXXX XXXXXX (XXX37U56T)`

2. App B - works.
`Identifier=com.xxxx.Xxx.qa`
`Format=bundle with Mach-O universal (armv7 arm64)`
`CodeDirectory v=20200 size=24800 flags=0x0(none) hashes=1231+5 location=embedded`
`Signature size=4330`
`Authority=iPhone Developer: Xxxx Xxxx (XXXJ4M8SK4)`

3. App C - works.
`Identifier=com.xxxxxxxx`
`Format=bundle with Mach-O universal (armv7 arm64)`
`CodeDirectory v=20200 size=44000 flags=0x0(none) hashes=2191+5 location=embedded`
`Signature size=4357`
`Authority=iPhone Distribution: Xxxx Xxxx LLC (XXXXNEAKDC)`

4. App D - doesn't work.
`Identifier=com.xxxxxxxxx.iphone`
`Format=bundle with Mach-O universal (armv7 arm64)`
`CodeDirectory v=20200 size=66647 flags=0x0(none) hashes=3323+5 location=embedded`
`Signature size=4339`
`Authority=iPhone Distribution: X&X Xxxx Xxxx (XXXXHPMQ8Y)`

**Comment by jmoody** [comment]
The .ipa must be signed by a _developer_ account.  App D is not signed by a developer, so UIAutomation cannot connect to it.

> resigning with briar

If the apps have extensions, then briar may or may not work.

Contact me privately via my GitHub email and I will see if I provide you with more details about resigning.

**Comment by ysilyutin** [comment]
I've checked the app with the Xcode/Instruments/Automation and I'm able to start the app, touch the elements, enter text and so on by using script in Automation. It means that the problem most likely related to the calabash server integration in the Xcode project. Just need to find a root of this issue.

**Comment by jmoody** [comment]
My best guess is that briar is not signing the app correctly.  There are known problems with resigning apps with extensions.

**Comment by ysilyutin** [comment]
Thank you for your help, Josh! Appreciate it.

**Comment by ysilyutin** [comment]
Hi Joshua,

it seems like resigning with briar is not the issue, because:

- Even before resigning the issue persists. The app was build and launched from the developer machine and trying to run 'calabash-ios console' gave the same issue 'stuck on splash screen'

- The app works fine if we reboot a device and start it manually, then we tried 'calabash-ios console' on the opening app and we are able to query the elements. But if we start 'start_test_server_in_background', we don't get any output in terminal.

Maybe you have any idea? Have you faced with something like this? Looks like we are getting some conflicts there. Thank you in advance and let us know if you need any additional information.

**Comment by jmoody** [comment]
There are known bugs in Apple's ScriptAgent which is ultimately to blame for this problem.

I see this all the time on my devices.  I am just as stumped as you.

**Comment by ysilyutin** [comment]
Thank you, Joshua. One little question. Is it a bug in the Apple's ScriptAgent on the developer side? Want to mention that I've tried different Xcode versions during testing, but got the same issue. Also as I said previously we have a problem with couple apps which were build specifically on Xcode 7.1.1. Do you think it's related to the problem? Appreciate your quick response.

**Comment by jmoody** [comment]
> on the developer side.

I am not sure I understand the question.   Apple is responsible for ScriptAgent.  My radars on this topic have come back as `Open Duplicate`.

**Comment by jmoody** [comment]
I have not seen any 7.1.1 related failures.

**Comment by TheChell** [comment]
We are seeing this on one of our tester's machines. 

Xcode version: 7.2.1
Mac OS X version: 10.10.5
calabash-cucumber version: 0.17.1

Device log snippet
```
Feb 26 10:00:44 iPhone MobileGestaltHelper[79] <Error>: libMobileGestalt MobileGestalt.c:273: server_access_check denied access to question UniqueDeviceID for pid 423
Feb 26 10:00:44 iPhone ScriptAgent[423] <Error>: libMobileGestalt MobileGestaltSupport.m:170: pid 423 (ScriptAgent) does not have sandbox access for re6Zb+zwFKJNlkQTUeT+/w and IS NOT appropriately entitled
Feb 26 10:00:44 iPhone ScriptAgent[423] <Error>: libMobileGestalt MobileGestalt.c:534: no access to UniqueDeviceID (see <rdar://problem/11744455>)
Feb 26 10:00:44 iPhone geod[121] <Warning>: Can't get bundle identifier for process 58
```

When I take the same device with the same app installed on it and attempt to run a test on my machine, it runs fine. This tells me it is not related to the app's signature. I am seeing the same issue @ysilyutin saw, where the app starts normally but just hangs on the splash screen without producing any errors or output in the terminal. When I start the test server in the console, the same thing happens (just hangs on starting the test server). 

I've tried rebooting the device, Xcode and the machine. I've also tried uninstalling and reinstalling Xcode completely, but to no avail. Has anyone found a solution yet?

**Comment by jmoody** [comment]
There is no solution.  This is a bug in Apple's script agent.  As far as we
know this does not block Calabash.  This error can appear and tests can
still run.

However we have seen examples where touching outside the bounds or close to
the edge of the screen can trigger this error and block Calabash.

Apple has not responded to our radars.

**Comment by khmereshop** [comment]
I got the same error. Apple App Store reject my App when I try to publish it with google AdMob

**Comment by jmoody** [comment]
@khmereshop 

This issue does not have anything to do with your rejection.   With that said, apps linked with Calabash _will be rejected by Apple_ because the calabash.framework contains private symbols.

We are no longer using UIAutomation, so this issue can be closed.
