### ISSUE TITLE
Can allow user to choose "not quit process" when relaunch?

### ISSUE THREAD

**Issue by Joyce-Qu** [calabash/run_loop#459]
Can set a option to let user choose "not quit launched process" when relaunch?
Want to do 2 iOS test case, so use calabash-ios to launch app on two ios devices. First I have launched device1, after that I want to launch device2, then I found that the app on device1 has been killed before device2 launched. 
it was worked fine with run_loop0.2.1, but it failed after updated code to run_loop2.1.1.
Found that "self.log_run_loop_options" has called "instruments.kill_instruments(xcode)", and seems that "kill_instruments" not only kill instruments process but also quit app, but in my case I don't want to close the app which has already launched.
If can provide a option to choose this action will be greatly appreciated.

**Comment by jmoody** [comment]
This feature is often requested.

There is no way to keep two `instruments` processes alive at the same time.

You should check your Cucumber `After` hook.  Are you calling `calabash_exit`?

**Comment by Joyce-Qu** [comment]
No, I haven't call calabash_exit.
I understand that it can only open one instruments instance at the same time. But I just want to use instruments to launch app at different time. Is there any way to kill instruments process but not close the launched app?
The two ios case has launched successful before I updated cucumber/run_loop.
And the Xcode version(7.3) is same.

**Comment by jmoody** [comment]
Since `instruments` launched the app, when it is terminated the app is also terminated.

There is no way to tell instruments to keep the app running after instruments is exited.

Some users have reported they can have multiple instruments processes running.  You could try for yourself by monkey patching RunLoop::Instruments#kill_instruments to be a no op.

We have found that we cannot keep the system stable with more than one instruments process.

**Comment by Joyce-Qu** [comment]
OK, Got that. Thanks anyway.
